### PR TITLE
WIP: [misc] bump requirements

### PR DESCRIPTION
**Pull request by das7pad**
dependabot found 2 outdated requirements:
- google-api-python-client
- pytest

pip-compile found 12:
- atomicwrites
- cachetools
- decorator
- google-api-python-client
- numpy
- oauthlib
- pyasn1-modules
- pytest
- soupsieve
- tqdm
- typed-ast
- wraped

### CODE REVIEW

**Comment by das7pad** [comment]
Hello @dependabot team,

Can you take a look at this project please?

The fix for #95 might be incomplete.

**Comment by das7pad** [comment]
Hey @greysteil, could you take a look at this issue please?

**Comment by greysteil** [comment]
Hmmm, can you confirm that the additional dependencies are top-level (i.e., they're included in a `req.in` file somewhere, rather than just is a `req.txt` file)? By default, Dependabot only creates PRs for top-level dependencies (you can configure it to create PRs for sub-dependencies, too).

**Comment by das7pad** [comment]
Thank you for your response.

Yes, the additional updates are for indirect requirements.

How can I configure it to include these as well? I could not find a suitable option in the [docs](https://dependabot.com/blog/introducing-config-files/).

**Comment by greysteil** [comment]
Ah great - check out the `Example: all updates including indirect/sub-dependencies` section in those docs.

**Comment by das7pad** [comment]
Oh. Thanks for the additional pointer!

**Pull request closed without merging**
